# Generated by Django 4.0.3 on 2022-03-29 00:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='autorx',
            field=models.CharField(default='Nombre', max_length=60),
        ),
        migrations.AddField(
            model_name='post',
            name='fecha_creacion',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
