# Generated by Django 4.0.3 on 2022-03-29 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_users_post_autorx_post_fecha_creacion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
